# Generated by Django 3.0.2 on 2020-01-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
